### ISSUE TITLE
Set up Travis CI

### ISSUE THREAD

**Issue by fsteeg** [hbz/geodata#11]
To build and test automatically in pull requests.

**Comment by dr0i** [comment]
Set up travis. Please @philboeselager review.

**Comment by philboeselager** [comment]
The travis build still fails (https://travis-ci.org/hbz/geodata/builds/88792249#L692) due to the Elasticsearch setting (https://github.com/hbz/geodata/blob/issue-11-setUpTravis/app/controllers/geo/GeoElasticsearch.java#L25). The Elasticsearch configuration chosen can easily be amended to Travis Elasticsearch defaults.

**Comment by dr0i** [comment]
Yes, I think the code must be fixed as you say. The issue of this ticket was just to set up travis, not to make the code work in travis, I think. So I would say this ticket can be closed (as long as I set up travis correctly).

**Comment by fsteeg** [comment]
I think we should leave this open and only close it when the build works with travis in https://github.com/hbz/geodata/issues/14.
