### ISSUE TITLE
Split project structure (move frontend to /web)

### ISSUE THREAD

**Issue by philboeselager** [hbz/geodata#9]
@fsteeg I'm going to come by and ask you for the best how-to. Or maybe that is a good thing for our pair-programming?

**Comment by fsteeg** [comment]
In lobid-organisations the metafacture transformations are in the root of the repo, the Play app is in `web/`. Based on that, and since the geodata repo has no metafacture transformation, I'd suggest moving the entire thing into `web/` (to have a common structure, as we discussed), except for `.gitignore`, `LICENSE`, and `README`. But we can also look into this together after our vacations.

**Comment by fsteeg** [comment]
In lobid-organisations we actually merged the two projects into a single Play app, which includes the transformation, so we already have a common repo structure (_without_ a `web/` directory). Closing.
